name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ${RUNNER_DIR} --file Dockerfile --tag ghcr.io/ituitis20-arabaci19/docker-image-builder:latest
