name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      RUNNER_DIR: '/home/runner/work/docker-image-builder/docker-image-builder'
      VERSION: '1.0.1'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: | 
        docker build ${RUNNER_DIR} --file Dockerfile --tag ghcr.io/deneme/anaconda-dev:2020.02
        docker push ghcr.io/deneme/anaconda-dev:2020.02
